/*
    ChibiOS - Copyright (C) 2006-2026 Giovanni Di Sirio.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#ifndef MCUCONF_H
#define MCUCONF_H

#define CH32H41x_MCUCONF
#define CH32H417_MCUCONF

/*
 * NOTE: Peripheral enable defines (CH32_SERIAL_USE_*, CH32_SPI_USE_*,
 * CH32_I2C_USE_*, etc.) are generated by chibios_hwdef.py in hwdef.h.
 * Do NOT define them here to avoid redefinition errors.
 */

/*
 * System clock and timer settings.
 */

/* HEART beat timer uses TIM5 (32-bit timer on CH32H417) */
#ifndef CH32_ST_USE_TIMER
#define CH32_ST_USE_TIMER                   5
#endif

/* SDMMC clock frequency in Hz (HCLK = 100MHz for V3F) */
#define CH32_SDC_SDMMC_CLOCK               100000000

/* GPIO_PIN8 already defined in board.h */
/* #define GPIO_PIN8                          8 */

/* GPT driver uses TIM3 for 1MHz timer */
#define CH32_GPT_USE_TIM3                  TRUE

/* PWM driver enables */
#define CH32_PWM_USE_TIM1                  TRUE
#define CH32_PWM_USE_TIM3                  TRUE
#define CH32_PWM_USE_TIM4                  TRUE
#define CH32_PWM_USE_TIM5                  TRUE

/* ADC driver enables */
#define CH32_ADC_USE_ADC1                  TRUE

#endif /* MCUCONF_H */

/* Include STM32 compatibility macros */
#include "ch32_compat.h"
